spring:
  application:
    name: UBot-BE

  profiles:
    default: local

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

management:
  endpoints:
    web:
      exposure:
        include:
          - health