spring:
  application:
    name: UBot-BE

  profiles:
    default: local

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

management:
  endpoints:
    web:
      exposure:
        include:
          - health

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-millis: ${JWT_ACCESS_TOKEN_EXPIRATION_MILLIS:3600000}
    refresh-token-expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:14}