-- 검토용 SQL입니다. Flyway 자동 실행 경로에 두지 않았고, DB에 실행하지 않았습니다.
-- DB 담당자가 실제 DB/진행 중 마이그레이션과 조율하여 새 V 버전으로 반영해야 합니다.
-- 기존 V1~V11 파일을 수정하지 않습니다.
--
-- 최신 ERD와 구현 사이의 최소 보완:
-- 1. question_log.llm_question: 질문 생성 시 빈 문자열, 성공 시 완성된 답변 저장.
-- 2. answer_attempts_history.question_log_id: 사용자 소유권과 재시도 묶음 식별.
-- 3. PENDING: 여러 서버의 동시 재시도 중복 실행 방지 및 중단 작업 복구.
-- 4. 한 행은 한 번의 생성 시도. attempt_count는 최초 시도 1, 재시도 2/3.
--
-- 이미 동명의 테이블이 생성되어 있다면 이 CREATE를 그대로 실행하지 말고 ALTER 이행안을 작성합니다.
-- 기존 테이블/데이터를 삭제하거나 덮어쓰는 SQL은 포함하지 않습니다.

-- API 명세의 /chat/sessions를 지원하는 최소 세션 구조 제안입니다.
-- 세션은 질문 묶음/소유권 확인 용도이며 이전 대화를 LLM에 전달하지 않습니다.
-- 팀에서 세션 만료/종료 정책을 정하면 DB 담당자가 추가 조율해야 합니다.
CREATE TABLE chat_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chat_sessions_user ON chat_sessions(user_id);

ALTER TABLE question_log
    ADD COLUMN IF NOT EXISTS llm_question TEXT NOT NULL DEFAULT '';

-- 기존 질문 로그를 보존하기 위해 기존 행의 session_id는 NULL을 허용합니다.
-- 새 채팅 API는 항상 소유권을 검증한 session_id를 저장합니다.
ALTER TABLE question_log
    ADD COLUMN session_id BIGINT REFERENCES chat_sessions(session_id);

CREATE INDEX idx_question_log_session ON question_log(session_id);

CREATE TABLE answer_attempts_history (
    attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_log_id BIGINT NOT NULL REFERENCES question_log(id),
    attempt_count INTEGER NOT NULL CHECK (attempt_count BETWEEN 1 AND 3),
    question TEXT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'FAIL', 'SUCCESS')),
    llm_model VARCHAR(200),
    embedding_model VARCHAR(200),
    error_code VARCHAR(100),
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idempotency_key VARCHAR(64) NOT NULL,
    -- 최초 시도와 재시도 2/3은 같은 질문의 동일 키를 저장합니다.
    CONSTRAINT uq_chat_attempt_key_count UNIQUE (idempotency_key, attempt_count),
    CONSTRAINT uq_chat_question_attempt UNIQUE (question_log_id, attempt_count)
);

-- 최초 시도 키는 질문마다 고유해야 하지만, 그 질문의 재시도에는 재사용합니다.
CREATE UNIQUE INDEX uq_chat_initial_question_key
    ON answer_attempts_history(idempotency_key) WHERE attempt_count = 1;

CREATE UNIQUE INDEX uq_chat_question_pending
    ON answer_attempts_history(question_log_id) WHERE status = 'PENDING';
CREATE UNIQUE INDEX uq_chat_question_success
    ON answer_attempts_history(question_log_id) WHERE status = 'SUCCESS';
