-- DB 담당자 검토용. 개발 DB에 실행하지 않으며 Flyway 경로에도 두지 않습니다.
-- 기존 V1~V11과 팀원의 FAQ 테이블은 유지합니다. 새 V 번호는 담당자가 결정합니다.
-- 세션은 사용하지 않습니다.
-- 사용자 소유권 확인에 user_id가 필요합니다. PENDING은 중복 재시도 차단용입니다.
-- 기존 answer_attempts_history가 있다면 담당자가 해당 스키마에 맞는 ALTER를 작성해야 합니다.

ALTER TABLE question_log ADD COLUMN IF NOT EXISTS llm_question TEXT NOT NULL DEFAULT '';

CREATE TABLE answer_attempts_history (
    attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    question TEXT NOT NULL,
    attempt_count INTEGER NOT NULL CHECK (attempt_count BETWEEN 1 AND 3),
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'FAIL', 'SUCCESS')),
    llm_model VARCHAR(200),
    embedding_model VARCHAR(200),
    error_code VARCHAR(100),
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idempotency_key VARCHAR(64) NOT NULL,
    CONSTRAINT uq_answer_attempt_key_count UNIQUE (idempotency_key, attempt_count)
);
