-- 채팅 통합 테스트 전용 스키마. Testcontainers 임시 DB에만 적용합니다.
-- 개발·운영 DB용 Flyway 마이그레이션은 DB 담당자와 확정합니다.

ALTER TABLE question_log ADD COLUMN IF NOT EXISTS llm_question TEXT NOT NULL DEFAULT '';

CREATE TABLE answer_attempts_history (
    attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    question TEXT NOT NULL,
    attempt_count INTEGER NOT NULL CHECK (attempt_count BETWEEN 1 AND 3),
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'FAIL', 'SUCCESS')),
    llm_model VARCHAR(200),
    embedding_model VARCHAR(200),
    error_code VARCHAR(100),
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idempotency_key VARCHAR(64) NOT NULL,
    CONSTRAINT uq_answer_attempt_key_count UNIQUE (idempotency_key, attempt_count)
);
