CREATE TABLE chat_sessions (
    session_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT REFERENCES users (user_id),
    guest_token_hash VARCHAR(255),
    expires_at       TIMESTAMP NOT NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at         TIMESTAMP
);

CREATE TABLE chat_questions (
    question_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        BIGINT         NOT NULL REFERENCES chat_sessions (session_id),
    client_request_id VARCHAR(64)    NOT NULL,
    question_text     TEXT           NOT NULL,
    intent            VARCHAR(30),
    location_text     VARCHAR(255),
    latitude          DECIMAL(10, 7),
    longitude         DECIMAL(10, 7),
    service_type_id   BIGINT REFERENCES service_types (service_type_id),
    created_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (session_id, client_request_id)
);

CREATE TABLE answer_attempts (
    attempt_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id         BIGINT      NOT NULL REFERENCES chat_questions (question_id),
    attempt_no          INTEGER     NOT NULL,
    status              VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    answer_text         TEXT,
    llm_model           VARCHAR(200),
    embedding_model     VARCHAR(200),
    error_code          VARCHAR(100),
    error_message       TEXT,
    insufficient_reason TEXT,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          TIMESTAMP,
    completed_at        TIMESTAMP,
    UNIQUE (question_id, attempt_no)
);

CREATE INDEX idx_chat_sessions_user_id ON chat_sessions (user_id);
