CREATE TABLE unanswered_questions (
    unanswered_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id   BIGINT      NOT NULL UNIQUE REFERENCES chat_questions (question_id),
    status        VARCHAR(20) NOT NULL DEFAULT 'NEW',
    admin_id      BIGINT REFERENCES users (user_id),
    faq_id        BIGINT REFERENCES faq (id),
    memo          TEXT,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at   TIMESTAMP
);

CREATE INDEX idx_unanswered_questions_status ON unanswered_questions (status, created_at DESC);
