ALTER TABLE question_log ADD COLUMN llm_question TEXT NOT NULL DEFAULT '';

CREATE TABLE answer_attempts_history (
    attempt_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (user_id),
    question        TEXT         NOT NULL,
    attempt_count   INTEGER      NOT NULL CHECK (attempt_count >= 1),
    status          VARCHAR(40)  NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'FAIL', 'SUCCESS')),
    idempotency_key VARCHAR(64)  NOT NULL,
    llm_model       VARCHAR(200),
    embedding_model VARCHAR(200),
    error_code      VARCHAR(100),
    error_message   TEXT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (idempotency_key, attempt_count)
);
