ALTER TABLE faq ADD COLUMN intent VARCHAR(20) NOT NULL DEFAULT 'GENERAL' CHECK (intent IN ('GENERAL', 'STORE_DATA', 'USER_DATA'));

ALTER TABLE old_faq ADD COLUMN intent VARCHAR(20) NOT NULL DEFAULT 'GENERAL' CHECK (intent IN ('GENERAL', 'STORE_DATA', 'USER_DATA'));
