CREATE TABLE unanswered_question_groups (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    representative_question TEXT         NOT NULL,
    centroid                vector(1024) NOT NULL,
    question_count          INTEGER      NOT NULL DEFAULT 1 CHECK (question_count >= 1),
    related_faq_id          BIGINT       REFERENCES faq (id),
    status                  VARCHAR(20)  NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'ON_HOLD', 'REJECTED')),
    last_occurred_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE unanswered_questions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id      BIGINT           NOT NULL UNIQUE REFERENCES answer_attempts_history (attempt_id),
    group_id        BIGINT           NOT NULL REFERENCES unanswered_question_groups (id),
    question        TEXT             NOT NULL,
    question_vector vector(1024)     NOT NULL,
    reason          VARCHAR(20)      NOT NULL CHECK (reason IN ('NO_FAQ', 'INSUFFICIENT_FAQ')),
    best_faq_id     BIGINT           REFERENCES faq (id),
    best_similarity DOUBLE PRECISION,
    created_at      TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_unanswered_questions_group_id ON unanswered_questions (group_id);
