ALTER TABLE question_log ADD COLUMN normalized_question TEXT NOT NULL DEFAULT '';

CREATE TABLE regional_trend_ranking_policy (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name               VARCHAR(20)      NOT NULL UNIQUE,
    min_current_search_count  INTEGER          NOT NULL,
    min_baseline_sample_count INTEGER          NOT NULL,
    trend_ratio_threshold     DOUBLE PRECISION NOT NULL
);
