CREATE TABLE conversations (
    conversation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID        NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    user_id         BIGINT      REFERENCES users (user_id),
    type            VARCHAR(20) NOT NULL CHECK (type IN ('GUEST', 'MEMBER')),
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (type = 'GUEST' OR user_id IS NOT NULL)
);

ALTER TABLE question_log ADD COLUMN conversation_id BIGINT REFERENCES conversations (conversation_id);
CREATE INDEX idx_question_log_conversation_id ON question_log (conversation_id);

ALTER TABLE answer_attempts_history ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE answer_attempts_history ADD COLUMN conversation_id BIGINT REFERENCES conversations (conversation_id);
ALTER TABLE answer_attempts_history ADD CONSTRAINT answer_attempts_history_owner_check
    CHECK (user_id IS NOT NULL OR conversation_id IS NOT NULL);
CREATE INDEX idx_answer_attempts_history_conversation_id ON answer_attempts_history (conversation_id);

CREATE TABLE guest_chat_settings (
    id                 BIGINT    PRIMARY KEY CHECK (id = 1),
    max_question_count INTEGER   NOT NULL CHECK (max_question_count >= 1),
    updated_by         BIGINT    REFERENCES users (user_id),
    updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO guest_chat_settings (id, max_question_count) VALUES (1, 5);
