CREATE TABLE store_reservations (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users (user_id),
    store_id       BIGINT      NOT NULL REFERENCES stores (store_id),
    purpose        VARCHAR(30) NOT NULL CHECK (purpose IN (
                       'PURCHASE_CONSULTING', 'PLAN_CHANGE', 'DEVICE_CHANGE', 'ACTIVATION',
                       'OWNERSHIP_TRANSFER', 'USIM_REPLACEMENT', 'LOSS_DAMAGE_REPORT'
                   )),
    visit_at       TIMESTAMP   NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'RESERVED'
                       CHECK (status IN ('RESERVED', 'CANCELED', 'COMPLETED', 'NO_SHOW')),
    created_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canceled_at    TIMESTAMP
);

CREATE UNIQUE INDEX uq_store_reservations_store_slot ON store_reservations (store_id, visit_at)
    WHERE status = 'RESERVED';
CREATE UNIQUE INDEX uq_store_reservations_user_slot ON store_reservations (user_id, visit_at)
    WHERE status = 'RESERVED';
CREATE INDEX idx_store_reservations_store_visit_at ON store_reservations (store_id, visit_at);
CREATE INDEX idx_store_reservations_user_visit_at ON store_reservations (user_id, visit_at);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (user_id),
    type            VARCHAR(40)  NOT NULL CHECK (type IN ('RESERVATION_CONFIRMED', 'RESERVATION_CANCELED')),
    title           VARCHAR(100) NOT NULL,
    message         VARCHAR(500) NOT NULL,
    reservation_id  BIGINT       REFERENCES store_reservations (reservation_id),
    read_at         TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notifications_user_created_at ON notifications (user_id, created_at);
