CREATE TABLE embedding_profiles (
    profile_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider        VARCHAR(30)  NOT NULL CHECK (provider IN ('ollama', 'openai-compatible')),
    model_name      VARCHAR(255) NOT NULL,
    dimensions      INTEGER      NOT NULL CHECK (dimensions = 1024),
    profile_version INTEGER      NOT NULL DEFAULT 1 CHECK (profile_version >= 1),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, model_name, dimensions, profile_version)
);

CREATE TABLE faq_embeddings (
    faq_id      BIGINT       NOT NULL REFERENCES faq (id) ON DELETE CASCADE,
    profile_id  BIGINT       NOT NULL REFERENCES embedding_profiles (profile_id),
    vector_type VARCHAR(20)  NOT NULL CHECK (vector_type IN ('QUESTION', 'ANSWER', 'QUESTION_ANSWER')),
    faq_version INTEGER      NOT NULL,
    vector      vector(1024) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (faq_id, profile_id, vector_type)
);

CREATE INDEX idx_faq_embeddings_vector_hnsw ON faq_embeddings USING hnsw (vector vector_cosine_ops);

CREATE TABLE unanswered_question_embeddings (
    question_id BIGINT       NOT NULL REFERENCES unanswered_questions (id) ON DELETE CASCADE,
    profile_id  BIGINT       NOT NULL REFERENCES embedding_profiles (profile_id),
    vector      vector(1024) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (question_id, profile_id)
);

CREATE TABLE unanswered_group_embeddings (
    group_id   BIGINT       NOT NULL REFERENCES unanswered_question_groups (id) ON DELETE CASCADE,
    profile_id BIGINT       NOT NULL REFERENCES embedding_profiles (profile_id),
    centroid   vector(1024) NOT NULL,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (group_id, profile_id)
);
