CREATE TABLE plans (
    plan_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code            VARCHAR(50)  NOT NULL UNIQUE,
    name                 VARCHAR(150) NOT NULL,
    description          TEXT,
    network_type         VARCHAR(20)  NOT NULL CHECK (network_type IN ('FIVE_G', 'LTE')),
    target_group         VARCHAR(20)  NOT NULL CHECK (target_group IN ('GENERAL', 'YOUTH', 'SENIOR', 'KIDS', 'WATCH', 'TABLET')),
    monthly_fee          INTEGER      NOT NULL CHECK (monthly_fee >= 0),
    data_amount_mb       BIGINT,
    data_unlimited       BOOLEAN      NOT NULL DEFAULT FALSE,
    exhausted_speed_kbps INTEGER      CHECK (exhausted_speed_kbps > 0),
    voice_minutes        INTEGER,
    voice_unlimited      BOOLEAN      NOT NULL DEFAULT FALSE,
    sms_count            INTEGER,
    sms_unlimited        BOOLEAN      NOT NULL DEFAULT FALSE,
    tethering_amount_mb  BIGINT       NOT NULL DEFAULT 0 CHECK (tethering_amount_mb >= 0),
    min_age              INTEGER      CHECK (min_age BETWEEN 0 AND 120),
    max_age              INTEGER      CHECK (max_age BETWEEN 0 AND 120),
    status               VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_by           BIGINT       REFERENCES users (user_id),
    updated_by           BIGINT       REFERENCES users (user_id),
    deleted_at           TIMESTAMP,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (min_age IS NULL OR max_age IS NULL OR min_age <= max_age),
    CHECK (
        (data_unlimited AND data_amount_mb IS NULL AND exhausted_speed_kbps IS NULL)
        OR (NOT data_unlimited AND data_amount_mb IS NOT NULL AND data_amount_mb >= 0)
    ),
    CHECK (
        (voice_unlimited AND voice_minutes IS NULL)
        OR (NOT voice_unlimited AND voice_minutes IS NOT NULL AND voice_minutes >= 0)
    ),
    CHECK (
        (sms_unlimited AND sms_count IS NULL)
        OR (NOT sms_unlimited AND sms_count IS NOT NULL AND sms_count >= 0)
    )
);

CREATE TABLE bundle_products (
    bundle_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(50)  NOT NULL UNIQUE,
    name              VARCHAR(150) NOT NULL,
    description       TEXT,
    discount_amount   INTEGER      NOT NULL CHECK (discount_amount >= 0),
    status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_by        BIGINT       REFERENCES users (user_id),
    updated_by        BIGINT       REFERENCES users (user_id),
    deleted_at        TIMESTAMP,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE addon_services (
    addon_service_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(50)  NOT NULL UNIQUE,
    name             VARCHAR(150) NOT NULL,
    description      TEXT,
    monthly_fee      INTEGER      NOT NULL CHECK (monthly_fee >= 0),
    status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_by       BIGINT       REFERENCES users (user_id),
    updated_by       BIGINT       REFERENCES users (user_id),
    deleted_at       TIMESTAMP,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roaming_products (
    roaming_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(50)  NOT NULL UNIQUE,
    name               VARCHAR(150) NOT NULL,
    description        TEXT,
    daily_fee          INTEGER      NOT NULL CHECK (daily_fee >= 0),
    data_amount_mb     BIGINT       NOT NULL CHECK (data_amount_mb >= 0),
    country            VARCHAR(100) NOT NULL CHECK (length(trim(country)) > 0),
    status             VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_by         BIGINT       REFERENCES users (user_id),
    updated_by         BIGINT       REFERENCES users (user_id),
    deleted_at         TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_roaming_products_country ON roaming_products (country)
    WHERE status = 'ACTIVE' AND deleted_at IS NULL;
