CREATE TABLE subscriptions (
    subscription_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL REFERENCES users (user_id),
    plan_id            BIGINT      NOT NULL REFERENCES plans (plan_id),
    phone_number       VARCHAR(30) NOT NULL CHECK (length(trim(phone_number)) > 0),
    status             VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'TERMINATED')),
    activated_at       TIMESTAMP   NOT NULL,
    terminated_at      TIMESTAMP,
    sim_type           VARCHAR(20) CHECK (sim_type IN ('USIM', 'ESIM')),
    sim_identifier     VARCHAR(100),
    sim_status         VARCHAR(20) CHECK (sim_status IN ('ACTIVE', 'SUSPENDED', 'LOST', 'REPLACED', 'DEACTIVATED')),
    sim_activated_at   TIMESTAMP,
    sim_deactivated_at TIMESTAMP,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_subscriptions_termination CHECK (
        (status = 'TERMINATED' AND terminated_at IS NOT NULL AND terminated_at >= activated_at)
        OR (status IN ('ACTIVE', 'SUSPENDED') AND terminated_at IS NULL)
    ),
    CONSTRAINT ck_subscriptions_sim_fields CHECK (
        (sim_type IS NULL AND sim_identifier IS NULL AND sim_status IS NULL
            AND sim_activated_at IS NULL AND sim_deactivated_at IS NULL)
        OR (sim_type IS NOT NULL AND sim_identifier IS NOT NULL
            AND length(trim(sim_identifier)) > 0 AND sim_status IS NOT NULL
            AND sim_activated_at IS NOT NULL
            AND (sim_deactivated_at IS NULL OR sim_deactivated_at >= sim_activated_at))
    )
);

CREATE UNIQUE INDEX uq_subscriptions_phone_number_active ON subscriptions (phone_number)
    WHERE status <> 'TERMINATED';
CREATE INDEX idx_subscriptions_user_status ON subscriptions (user_id, status);
CREATE INDEX idx_subscriptions_plan ON subscriptions (plan_id);

CREATE TABLE usage_records (
    usage_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id         BIGINT    NOT NULL REFERENCES subscriptions (subscription_id),
    billing_month           DATE      NOT NULL CHECK (EXTRACT(DAY FROM billing_month) = 1),
    data_used_mb            BIGINT    NOT NULL DEFAULT 0 CHECK (data_used_mb >= 0),
    voice_used_minutes      INTEGER   NOT NULL DEFAULT 0 CHECK (voice_used_minutes >= 0),
    sms_used_count          INTEGER   NOT NULL DEFAULT 0 CHECK (sms_used_count >= 0),
    allowance_snapshot      JSONB     CHECK (allowance_snapshot IS NULL OR jsonb_typeof(allowance_snapshot) = 'object'),
    aggregated_through_date DATE,
    finalized_at            TIMESTAMP,
    full_month_active       BOOLEAN,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_usage_records_subscription_month UNIQUE (subscription_id, billing_month),
    CONSTRAINT ck_usage_records_aggregation_month CHECK (
        aggregated_through_date IS NULL
        OR (aggregated_through_date >= billing_month
            AND aggregated_through_date < (billing_month + INTERVAL '1 month')::DATE)
    ),
    CONSTRAINT ck_usage_records_finalization CHECK (
        finalized_at IS NULL
        OR (aggregated_through_date IS NOT NULL AND full_month_active IS NOT NULL
            AND aggregated_through_date = (billing_month + INTERVAL '1 month - 1 day')::DATE
            AND finalized_at::DATE >= aggregated_through_date)
    )
);

CREATE TABLE billing_records (
    billing_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT      NOT NULL REFERENCES subscriptions (subscription_id),
    billing_month   DATE        NOT NULL CHECK (EXTRACT(DAY FROM billing_month) = 1),
    base_fee        INTEGER     NOT NULL DEFAULT 0 CHECK (base_fee >= 0),
    addon_fee       INTEGER     NOT NULL DEFAULT 0 CHECK (addon_fee >= 0),
    roaming_fee     INTEGER     NOT NULL DEFAULT 0 CHECK (roaming_fee >= 0),
    extra_fee       INTEGER     NOT NULL DEFAULT 0 CHECK (extra_fee >= 0),
    discount_amount INTEGER     NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    total_amount    INTEGER     NOT NULL CHECK (total_amount >= 0),
    due_date        DATE,
    payment_status  VARCHAR(20) NOT NULL DEFAULT 'UNPAID' CHECK (payment_status IN ('UNPAID', 'PAID', 'OVERDUE')),
    paid_amount     INTEGER     NOT NULL DEFAULT 0 CHECK (paid_amount >= 0 AND paid_amount <= total_amount),
    payment_method  VARCHAR(20) CHECK (payment_method IN ('CARD', 'ACCOUNT', 'AUTO_TRANSFER', 'ETC')),
    paid_at         TIMESTAMP,
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_billing_records_subscription_month UNIQUE (subscription_id, billing_month),
    CONSTRAINT ck_billing_records_paid_total CHECK (
        payment_status <> 'PAID' OR paid_amount = total_amount
    ),
    CONSTRAINT ck_billing_records_payment_fields CHECK (
        (paid_amount = 0 AND payment_method IS NULL AND paid_at IS NULL)
        OR (paid_amount > 0 AND payment_method IS NOT NULL AND paid_at IS NOT NULL)
    )
);

CREATE INDEX idx_billing_records_payment_status ON billing_records (payment_status);

CREATE TABLE subscription_contracts (
    contract_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id              BIGINT       NOT NULL REFERENCES subscriptions (subscription_id),
    contract_type                VARCHAR(30)  NOT NULL CHECK (contract_type IN ('SELECTIVE_CONTRACT', 'DEVICE_SUBSIDY')),
    started_at                   DATE         NOT NULL,
    expires_at                   DATE         NOT NULL,
    discount_amount              INTEGER      NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    status                       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELED')),
    canceled_at                  TIMESTAMP,
    device_name                  VARCHAR(150),
    device_total_amount          INTEGER      CHECK (device_total_amount >= 0),
    installment_months           INTEGER      CHECK (installment_months > 0),
    paid_installment_months      INTEGER      CHECK (paid_installment_months >= 0),
    monthly_installment_amount   INTEGER      CHECK (monthly_installment_amount >= 0),
    remaining_installment_amount INTEGER      CHECK (remaining_installment_amount >= 0),
    installment_started_at       DATE,
    installment_expires_at       DATE,
    installment_status           VARCHAR(20)  CHECK (installment_status IN ('ACTIVE', 'COMPLETED', 'CANCELED')),
    created_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_subscription_contracts_period CHECK (started_at <= expires_at),
    CONSTRAINT ck_subscription_contracts_cancellation CHECK (
        (status = 'CANCELED' AND canceled_at IS NOT NULL AND canceled_at::DATE >= started_at)
        OR (status IN ('ACTIVE', 'EXPIRED') AND canceled_at IS NULL)
    ),
    CONSTRAINT ck_subscription_contracts_installment_fields CHECK (
        (device_name IS NULL AND device_total_amount IS NULL AND installment_months IS NULL
            AND paid_installment_months IS NULL AND monthly_installment_amount IS NULL
            AND remaining_installment_amount IS NULL AND installment_started_at IS NULL
            AND installment_expires_at IS NULL AND installment_status IS NULL)
        OR (device_name IS NOT NULL AND length(trim(device_name)) > 0
            AND device_total_amount IS NOT NULL AND installment_months IS NOT NULL
            AND paid_installment_months IS NOT NULL AND monthly_installment_amount IS NOT NULL
            AND remaining_installment_amount IS NOT NULL AND installment_started_at IS NOT NULL
            AND installment_expires_at IS NOT NULL AND installment_status IS NOT NULL
            AND paid_installment_months <= installment_months
            AND remaining_installment_amount <= device_total_amount
            AND installment_started_at <= installment_expires_at
            AND (installment_status <> 'COMPLETED' OR remaining_installment_amount = 0))
    )
);

CREATE INDEX idx_subscription_contracts_subscription ON subscription_contracts (subscription_id);
CREATE UNIQUE INDEX uq_subscription_contracts_active ON subscription_contracts (subscription_id)
    WHERE status = 'ACTIVE';

CREATE TABLE subscription_bundles (
    subscription_bundle_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id         BIGINT       NOT NULL REFERENCES subscriptions (subscription_id),
    bundle_product_id       BIGINT       NOT NULL REFERENCES bundle_products (bundle_product_id),
    joined_at               TIMESTAMP    NOT NULL,
    ended_at                TIMESTAMP,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ENDED')),
    product_name_snapshot   VARCHAR(150) NOT NULL CHECK (length(trim(product_name_snapshot)) > 0),
    applied_discount_amount INTEGER      NOT NULL CHECK (applied_discount_amount >= 0),
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_subscription_bundles_termination CHECK (
        (status = 'ENDED' AND ended_at IS NOT NULL AND ended_at >= joined_at)
        OR (status = 'ACTIVE' AND ended_at IS NULL)
    )
);

CREATE INDEX idx_subscription_bundles_product ON subscription_bundles (bundle_product_id);
CREATE INDEX idx_subscription_bundles_subscription_status ON subscription_bundles (subscription_id, status);
CREATE UNIQUE INDEX uq_subscription_bundles_active ON subscription_bundles (subscription_id)
    WHERE status = 'ACTIVE';

CREATE TABLE subscription_addons (
    subscription_addon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id       BIGINT       NOT NULL REFERENCES subscriptions (subscription_id),
    addon_service_id      BIGINT       NOT NULL REFERENCES addon_services (addon_service_id),
    subscribed_at         TIMESTAMP    NOT NULL,
    canceled_at           TIMESTAMP,
    status                VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CANCELED')),
    service_name_snapshot VARCHAR(150) NOT NULL CHECK (length(trim(service_name_snapshot)) > 0),
    monthly_fee_snapshot  INTEGER      NOT NULL CHECK (monthly_fee_snapshot >= 0),
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_subscription_addons_cancellation CHECK (
        (status = 'CANCELED' AND canceled_at IS NOT NULL AND canceled_at >= subscribed_at)
        OR (status = 'ACTIVE' AND canceled_at IS NULL)
    )
);

CREATE INDEX idx_subscription_addons_service ON subscription_addons (addon_service_id);
CREATE INDEX idx_subscription_addons_subscription_status ON subscription_addons (subscription_id, status);
CREATE UNIQUE INDEX uq_subscription_addons_active ON subscription_addons (subscription_id, addon_service_id)
    WHERE status = 'ACTIVE';

CREATE TABLE subscription_roamings (
    subscription_roaming_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id         BIGINT       NOT NULL REFERENCES subscriptions (subscription_id),
    roaming_product_id      BIGINT       NOT NULL REFERENCES roaming_products (roaming_product_id),
    start_date              DATE         NOT NULL,
    end_date                DATE         NOT NULL,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN ('SCHEDULED', 'ACTIVE', 'EXPIRED', 'CANCELED')),
    product_name_snapshot   VARCHAR(150) NOT NULL CHECK (length(trim(product_name_snapshot)) > 0),
    daily_fee_snapshot      INTEGER      NOT NULL CHECK (daily_fee_snapshot >= 0),
    data_amount_mb_snapshot BIGINT       NOT NULL CHECK (data_amount_mb_snapshot >= 0),
    canceled_at             TIMESTAMP,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_subscription_roamings_period CHECK (start_date <= end_date),
    CONSTRAINT ck_subscription_roamings_cancellation CHECK (
        (status = 'CANCELED' AND canceled_at IS NOT NULL)
        OR (status IN ('SCHEDULED', 'ACTIVE', 'EXPIRED') AND canceled_at IS NULL)
    )
);

CREATE INDEX idx_subscription_roamings_product ON subscription_roamings (roaming_product_id);
CREATE INDEX idx_subscription_roamings_subscription_status_date
    ON subscription_roamings (subscription_id, status, start_date);
