CREATE TABLE faq_category (
                              id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE faq (
                     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     category_id BIGINT       NOT NULL REFERENCES faq_category (id),
                     question    TEXT         NOT NULL,
                     answer      TEXT         NOT NULL,
                     vector      vector(1024),
                     created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     deleted_at  TIMESTAMP,
                     version     INTEGER      NOT NULL DEFAULT 1,
                     admin_id    BIGINT       -- users 테이블 생성 후 FK 추가
);

CREATE INDEX idx_faq_vector ON faq USING hnsw (vector vector_cosine_ops);

CREATE TABLE faq_old (
                         faq_id          BIGINT       NOT NULL REFERENCES faq (id),
                         version         INTEGER      NOT NULL,
                         category_id     BIGINT       NOT NULL REFERENCES faq_category (id),
                         question        TEXT         NOT NULL,
                         answer          TEXT         NOT NULL,
                         vector          vector(1024),
                         updated_at      TIMESTAMP    NOT NULL,
                         update_admin_id BIGINT,      -- users 테이블 생성 후 FK 추가
                         create_admin_id BIGINT,
                         PRIMARY KEY (faq_id, version)
);

CREATE TABLE question_log (
                              id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id       BIGINT,       -- users 테이블 생성 후 FK 추가
                              user_question TEXT      NOT NULL,
                              created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE faq_log (
                         id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         question_log_id BIGINT NOT NULL REFERENCES question_log (id),
                         faq_id          BIGINT NOT NULL REFERENCES faq (id),
                         rank            BIGINT,
                         similarity      DOUBLE PRECISION,
                         UNIQUE (question_log_id, rank)
);