ALTER TABLE faq_log ALTER COLUMN rank TYPE INTEGER;
ALTER TABLE faq_log ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE faq_category ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
