CREATE TABLE users (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    name           VARCHAR(100) NOT NULL,
    birth_date     DATE,
    gender         VARCHAR(20),
    residence_area VARCHAR(200),
    role           VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TIMESTAMP
);

CREATE UNIQUE INDEX uq_users_email_active ON users (email) WHERE deleted_at IS NULL;

ALTER TABLE faq ADD CONSTRAINT faq_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES users (user_id);
ALTER TABLE old_faq ADD CONSTRAINT old_faq_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (user_id);
ALTER TABLE old_faq ADD CONSTRAINT old_faq_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES users (user_id);
ALTER TABLE question_log ADD CONSTRAINT question_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (user_id);
